package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
)

const metaTemplate = `// Code generated by tools/modelprep. DO NOT EDIT.

package mlclassify

// Attack-label orientations for the embedded models, determined by the
// modelprep golden test at build time. The runtime reads these constants so it
// never guesses which label index means "attack".

// phase1AttackLabel is the attack label index for
// GuardrailsAI/prompt-saturation-attack-detector.
const phase1AttackLabel = 1

// phase2AttackLabel is the attack label index for
// jackhhao/jailbreak-classifier.
const phase2AttackLabel = 1
`

// writeMeta records one verified attack-label orientation into the generated
// assets_meta.go, preserving the other phase's value.
func writeMeta(phase string, attackLabel int) error {
	root, err := repoRoot()
	if err != nil {
		return err
	}
	path := filepath.Join(root, "internal", "mlclassify", "assets_meta.go")

	content := ""
	if data, err := os.ReadFile(path); err == nil {
		content = string(data)
	} else {
		content = metaTemplate
	}

	constName := "phase1AttackLabel"
	if phase == "phase2" {
		constName = "phase2AttackLabel"
	}

	re := regexp.MustCompile(`const ` + constName + ` = \d+`)
	if !re.MatchString(content) {
		return fmt.Errorf("%s: no %s constant to update", path, constName)
	}
	content = re.ReplaceAllString(content, "const "+constName+" = "+strconv.Itoa(attackLabel))

	return os.WriteFile(path, []byte(content), 0o644)
}
