package rolemanager

import (
	"fmt"
	"strings"

	"github.com/vulnetix/signet/internal/delimiters"
)

// TrustedSource identifies where a prompt fragment came from. Only fragments
// from trusted sources may enter system/agent blocks.
type TrustedSource string

const (
	// SourceHarness marks prompt fragments generated by the harness itself.
	SourceHarness TrustedSource = "harness"
	// SourceTool marks output from trusted internal tools (e.g. the Vulnetix
	// CLI), which is safe to promote.
	SourceTool TrustedSource = "tool"
)

// SystemBlock is a trusted fragment destined for a system/agent block.
type SystemBlock struct {
	Source  TrustedSource
	Content string
	// Kind is the delimiter kind the block is sealed as. Empty means
	// "system", which is what every block was before the field existed. A
	// non-empty kind must be a known harness kind: an unknown one would be
	// left untouched by Egress and so would reach the provider unsealed,
	// which is the one thing this boundary exists to prevent.
	Kind string
}

// isTrusted reports whether a source may enter system/agent blocks.
func isTrusted(s TrustedSource) bool {
	return s == SourceHarness || s == SourceTool
}

// Noncer reserves and validates nonces for sealed delimiters.
type Noncer interface {
	Reserve() (string, error)
	Valid(string) bool
}

// VerifyTrustedBlocks rejects any block not from a trusted source, and any
// block naming a delimiter kind the engine does not manage. This is the
// boundary that guarantees untrusted text never enters system or agent blocks.
func VerifyTrustedBlocks(blocks []SystemBlock) error {
	for _, b := range blocks {
		if !isTrusted(b.Source) {
			record("boundary_verify_failure", "", "", string(b.Source), 0)
			return fmt.Errorf("block from source %q may not enter system/agent blocks", b.Source)
		}
		if b.Kind != "" && !delimiters.KnownKinds[b.Kind] {
			record("boundary_verify_failure", "", "", b.Kind, 0)
			return fmt.Errorf("unknown delimiter kind %q", b.Kind)
		}
	}
	return nil
}

// blockKind resolves a block's delimiter kind, defaulting to "system".
func blockKind(b SystemBlock) string {
	if b.Kind == "" {
		return "system"
	}
	return b.Kind
}

// BuildSystemPrompt assembles the system/agent prompt from trusted blocks only.
// Each block is wrapped in a harness delimiter carrying a reserved nonce and a
// SHA-256 integrity hash of its content. The assembled prompt is verified with
// Egress so any forged or malformed block is stripped before it can leave.
func BuildSystemPrompt(blocks []SystemBlock, noncer Noncer) (string, error) {
	if err := VerifyTrustedBlocks(blocks); err != nil {
		return "", err
	}
	if noncer == nil {
		return "", fmt.Errorf("noncer is required")
	}
	record("boundary_seal", "", "", fmt.Sprintf("blocks=%d", len(blocks)), 0)
	var b strings.Builder
	for _, blk := range blocks {
		nonce, err := noncer.Reserve()
		if err != nil {
			return "", fmt.Errorf("reserve nonce: %w", err)
		}
		wrapped := delimiters.Wrap(blockKind(blk), nonce, blk.Content)
		b.WriteString(wrapped)
		b.WriteString("\n")
	}
	return delimiters.Egress(b.String(), noncer), nil
}
