package rolemanager

import (
	"fmt"
	"strings"
)

// TrustedSource identifies where a prompt fragment came from. Only fragments
// from trusted sources may enter system/agent blocks.
type TrustedSource string

const (
	// SourceHarness marks prompt fragments generated by the harness itself.
	SourceHarness TrustedSource = "harness"
	// SourceTool marks output from trusted internal tools (e.g. the Vulnetix
	// CLI), which is safe to promote.
	SourceTool TrustedSource = "tool"
)

// SystemBlock is a trusted fragment destined for a system/agent block.
type SystemBlock struct {
	Source  TrustedSource
	Content string
}

// isTrusted reports whether a source may enter system/agent blocks.
func isTrusted(s TrustedSource) bool {
	return s == SourceHarness || s == SourceTool
}

// VerifyTrustedBlocks rejects any block not from a trusted source. This is the
// boundary that guarantees untrusted text never enters system or agent blocks.
func VerifyTrustedBlocks(blocks []SystemBlock) error {
	for _, b := range blocks {
		if !isTrusted(b.Source) {
			return fmt.Errorf("block from source %q may not enter system/agent blocks", b.Source)
		}
	}
	return nil
}

// BuildSystemPrompt assembles the system/agent prompt from trusted blocks only.
func BuildSystemPrompt(blocks []SystemBlock) (string, error) {
	if err := VerifyTrustedBlocks(blocks); err != nil {
		return "", err
	}
	var b strings.Builder
	for _, blk := range blocks {
		b.WriteString(blk.Content)
		b.WriteString("\n")
	}
	return b.String(), nil
}
