// Code generated by tools/modelprep. DO NOT EDIT.

package mlclassify

// Attack-label orientations for the embedded models, determined by the
// modelprep golden test at build time. The runtime reads these constants so it
// never guesses which label index means "attack".

// phase1AttackLabel is the attack label index for
// GuardrailsAI/prompt-saturation-attack-detector.
const phase1AttackLabel = 1

// phase2AttackLabel is the attack label index for
// leomaurodesenv/bert-base-uncased-trustairlab-jailbreak.
const phase2AttackLabel = 1
